// @ts-check
import { defineConfig } from 'astro/config';

import react from '@astrojs/react';
import tailwindcss from '@tailwindcss/vite';

// Sitemap is generated by src/pages/sitemap.xml.ts as a single file rather
// than @astrojs/sitemap's index + chunk pair.

// https://astro.build/config
export default defineConfig({
  site: 'https://www.lotterytaxcalculator.co.uk',
  integrations: [react()],

  vite: {
    plugins: [tailwindcss()]
  }
});